mark_as_advanced(LUNCHBOX_PACKAGE_VERSION)

set(CPACK_PACKAGE_VENDOR "")
set(CPACK_PACKAGE_CONTACT "Juan Morales <juan.morales@upm.es>")
#set(CPACK_PACKAGE_DESCRIPTION_FILE ${CMAKE_SOURCE_DIR}/README.md)
set(CPACK_RESOURCE_FILE_README ${CMAKE_SOURCE_DIR}/README.md)

#set(CPACK_DEBIAN_PACKAGE_DEPENDS )

include(CommonCPack)


